[package]
name = "lib-sim-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.100"
lib-simulation = { path = "../sims" }
getrandom = { version = "0.2.16", features = ["js"] }
rand = "0.8.5"

[lib]
crate-type = ["cdylib"]


